# Some of the CRAN servers have pandoc installed and some do not, thus any test
# that builds an R Markdown file needs to be skipped with skip_on_cran(). This
# CI build does not have pandoc installed, so it will identify any tests that
# require pandoc but aren't skipped.
version: 2
jobs:
  release:
    environment:
      NOT_CRAN: true
      PANDOC: 2.7
    docker:
      - image: rocker/r-ver:3.6.0
    steps:
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}
      - checkout
      - run:
          name: Install system dependencies
          command: bash .circleci/install-system.sh
      - run:
          name: Install pandoc
          command: bash .circleci/install-pandoc.sh $PANDOC
      - run:
          name: Install package dependencies
          command: r .circleci/install-r-pkgs.R
      - run:
          name: Session information and installed package versions
          command: r -p .circleci/session-info.R
      - run:
          name: Build and check
          command: bash .circleci/check.sh
      - store_artifacts:
          path: workflowr.Rcheck/
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}
          paths:
            - "/usr/local/lib/R/site-library"
  devel:
    environment:
      NOT_CRAN: true
      PANDOC: 2.7
    docker:
      - image: rocker/r-ver:devel
    steps:
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}
      - checkout
      - run:
          name: Install system dependencies
          command: bash .circleci/install-system.sh
      - run:
          name: Install pandoc
          command: bash .circleci/install-pandoc.sh $PANDOC
      - run:
          name: Install package dependencies
          command: r .circleci/install-r-pkgs.R
      - run:
          name: Session information and installed package versions
          command: r -p .circleci/session-info.R
      - run:
          name: Build and check
          command: bash .circleci/check.sh
      - store_artifacts:
          path: workflowr.Rcheck/
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}
          paths:
            - "/usr/local/lib/R/site-library"
  oldrel:
    environment:
      NOT_CRAN: true
      PANDOC: 2.7
    docker:
      - image: rocker/r-ver:3.5.3
    steps:
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}
      - checkout
      - run:
          name: Install system dependencies
          command: bash .circleci/install-system.sh
      - run:
          name: Install pandoc
          command: bash .circleci/install-pandoc.sh $PANDOC
      - run:
          name: Install package dependencies
          command: r .circleci/install-r-pkgs.R
      - run:
          name: Session information and installed package versions
          command: r -p .circleci/session-info.R
      - run:
          name: Build and check
          command: bash .circleci/check.sh
      - store_artifacts:
          path: workflowr.Rcheck/
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}
          paths:
            - "/usr/local/lib/R/site-library"
  pandocless:
    docker:
      - image: rocker/r-ver:3.6.0
    steps:
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}
      - checkout
      - run:
          name: Install system dependencies
          command: bash .circleci/install-system.sh
      - run:
          name: Install package dependencies
          command: r .circleci/install-r-pkgs.R
      - run:
          name: Session information and installed package versions
          command: r -p .circleci/session-info.R
      - run:
          name: Build and check
          command: bash .circleci/check.sh
      - store_artifacts:
          path: workflowr.Rcheck/
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}
          paths:
            - "/usr/local/lib/R/site-library"
  pandoc_one:
    environment:
      NOT_CRAN: true
      PANDOC: 1.19
    docker:
      - image: rocker/r-ver:3.6.0
    steps:
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}
      - checkout
      - run:
          name: Install system dependencies
          command: bash .circleci/install-system.sh
      - run:
          name: Install pandoc
          command: bash .circleci/install-pandoc.sh $PANDOC
      - run:
          name: Install package dependencies
          command: r .circleci/install-r-pkgs.R
      - run:
          name: Session information and installed package versions
          command: r -p .circleci/session-info.R
      - run:
          name: Build and check
          command: bash .circleci/check.sh
      - store_artifacts:
          path: workflowr.Rcheck/
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}
          paths:
            - "/usr/local/lib/R/site-library"
  git2r_0.21.0:
    environment:
      NOT_CRAN: true
      PANDOC: 2.7
    docker:
      - image: rocker/r-ver:3.6.0
    steps:
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}
      - checkout
      - run:
          name: Install system dependencies
          command: bash .circleci/install-system.sh
      - run:
          name: Install pandoc
          command: bash .circleci/install-pandoc.sh $PANDOC
      - run:
          name: Install package dependencies
          command: r .circleci/install-r-pkgs.R
      - run:
          name: Install git2r 0.21.0
          command: r -e 'remotes::install_version("git2r", "0.21.0")'
      - run:
          name: Session information and installed package versions
          command: r -p .circleci/session-info.R
      - run:
          name: Build and check
          command: bash .circleci/check.sh
      - store_artifacts:
          path: workflowr.Rcheck/
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}
          paths:
            - "/usr/local/lib/R/site-library"
  rmd_1.7:
    environment:
      NOT_CRAN: true
      PANDOC: 2.7
    docker:
      - image: rocker/r-ver:3.6.0
    steps:
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}
      - checkout
      - run:
          name: Install system dependencies
          command: bash .circleci/install-system.sh
      - run:
          name: Install pandoc
          command: bash .circleci/install-pandoc.sh $PANDOC
      - run:
          name: Install package dependencies
          command: r .circleci/install-r-pkgs.R
      - run:
          name: Install knitr 1.18 and rmarkdown 1.7
          command: |
            r -e 'remotes::install_version("knitr", "1.18", upgrade = FALSE)'
            r -e 'remotes::install_version("rmarkdown", "1.7", upgrade = FALSE)'
      - run:
          name: Session information and installed package versions
          command: r -p .circleci/session-info.R
      - run:
          name: Build and check
          command: bash .circleci/check.sh
      - store_artifacts:
          path: workflowr.Rcheck/
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}
          paths:
            - "/usr/local/lib/R/site-library"
  codecov:
    environment:
      NOT_CRAN: true
      PANDOC: 2.7
    docker:
      - image: rocker/r-ver:3.6.0
    steps:
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}
      - checkout
      - run:
          name: Install system dependencies
          command: bash .circleci/install-system.sh
      - run:
          name: Install pandoc
          command: bash .circleci/install-pandoc.sh $PANDOC
      - run:
          name: Install package dependencies
          command: r .circleci/install-r-pkgs.R
      - run:
          name: Session information and installed package versions
          command: r -p .circleci/session-info.R
      - run:
          name: Calculate code coverage
          command: r -e 'covr::codecov()'
      - store_artifacts:
          path: workflowr.Rcheck/
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}
          paths:
            - "/usr/local/lib/R/site-library"
workflows:
  version: 2
  all:
    jobs:
      - release
      - devel
      - oldrel
      - pandocless
      - pandoc_one
      - git2r_0.21.0
      - rmd_1.7
      - codecov
